# Generated by Django 5.2.4 on 2025-07-10 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rag', '0002_chatmessage_chatragcontext'),
    ]

    operations = [
        migrations.CreateModel(
            name='RAGEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('embedding', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='chat_rag.ragdocument')),
            ],
            options={
                'ordering': ['document_id', 'chunk_index'],
                'indexes': [models.Index(fields=['document'], name='chat_rag_ra_documen_480796_idx'), models.Index(fields=['document', 'chunk_index'], name='chat_rag_ra_documen_5efded_idx')],
            },
        ),
    ]
