# Generated by Django 5.2.4 on 2025-07-10 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_rag', '0003_ragembedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatragcontext',
            name='document_chunk',
        ),
        migrations.AddField(
            model_name='chatragcontext',
            name='embedding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rag_contexts', to='chat_rag.ragembedding'),
        ),
        migrations.DeleteModel(
            name='RAGDocumentChunk',
        ),
    ]
