# Generated by Django 5.2.4 on 2025-07-09 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LangGraphMemoryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_conversations', models.PositiveIntegerField(default=0)),
                ('total_checkpoints', models.PositiveIntegerField(default=0)),
                ('active_conversations', models.PositiveIntegerField(default=0)),
                ('avg_checkpoints_per_conversation', models.FloatField(default=0.0)),
                ('total_memory_mb', models.FloatField(default=0.0)),
                ('avg_response_time_ms', models.FloatField(default=0.0)),
                ('total_api_calls', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LangGraphCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, help_text='Chat session identifier', max_length=255)),
                ('checkpoint_id', models.CharField(help_text='Unique checkpoint identifier', max_length=255)),
                ('parent_checkpoint_id', models.CharField(blank=True, help_text='Parent checkpoint for versioning', max_length=255, null=True)),
                ('checkpoint_data', models.JSONField(help_text='Serialized checkpoint state')),
                ('metadata', models.JSONField(default=dict, help_text='Checkpoint metadata')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['thread_id', '-created_at'], name='app_langgra_thread__0c55bd_idx'), models.Index(fields=['checkpoint_id'], name='app_langgra_checkpo_91f32c_idx')],
                'unique_together': {('thread_id', 'checkpoint_id')},
            },
        ),
        migrations.CreateModel(
            name='LangGraphConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(help_text='LangGraph thread identifier', max_length=255, unique=True)),
                ('current_checkpoint_id', models.CharField(blank=True, max_length=255, null=True)),
                ('message_count', models.PositiveIntegerField(default=0, help_text='Number of messages in conversation')),
                ('context_summary', models.TextField(blank=True, help_text='Summary of conversation context')),
                ('user_context', models.JSONField(default=dict, help_text='User-specific context data')),
                ('is_active', models.BooleanField(default=True, help_text='Whether conversation is currently active')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='langgraph_state', to='app.chat')),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['thread_id'], name='app_langgra_thread__bfb342_idx'), models.Index(fields=['is_active', '-last_activity'], name='app_langgra_is_acti_f22db0_idx')],
            },
        ),
    ]
