# Generated by Django 5.2.4 on 2025-07-09 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_langgraphmemorystats_langgraphcheckpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langgraphconversationstate',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='langgraph_state', to='app.chat'),
        ),
    ]
